cp /home/victor/pulp_shared_vm/pulp_box/pulpissimo/rtl/includes/*.*v* include
cp /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/common_cells/include/*.*v* include
cp /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/cluster_interconnect/rtl/low_latency_interco/*.*v* include
cp /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/cluster_interconnect/rtl/peripheral_interco/*.*v* include 
cp /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/cluster_interconnect/../../rtl/includes/*.*v* include 
cp /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/adv_dbg_if/rtl/*.*v* include
cp /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/apb/apb_adv_timer/./rtl/*.*v* include
cp /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/axi/axi/include/*.*v* include 
cp /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/axi/axi/../../common_cells/include/*.*v* include 
cp /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/timer_unit/rtl/*.*v* include 
cp /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/fpnew/../common_cells/include/*.*v* include 
cp /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/jtag_pulp/../../rtl/includes/*.*v* include 
cp /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/riscv/./rtl/include/*.*v* include 
cp /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/riscv/../../rtl/includes/*.*v* include 
cp /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/riscv/./rtl/include/*.*v* include 
cp /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/ibex/rtl/*.*v* include 
cp /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/ibex/shared/rtl/*.*v* include 
cp /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/udma/udma_core/./rtl/*.*v* include 
cp /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/udma/udma_qspi/rtl/*.*v* include 
cp /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/hwpe-ctrl/rtl/*.*v* include 
cp /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/hwpe-stream/rtl/*.*v* include 
cp /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/hwpe-mac-engine/rtl/*.*v* include 
cp /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/register_interface/include/*.*v* include 
cp /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/register_interface/../axi/axi/include/*.*v* include 
cp /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/register_interface/../common_cells/include/*.*v* include 
cp /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/register_interface/include/*.*v* include 
cp /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/register_interface/../axi/axi/include/*.*v* include 
cp /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/register_interface/../common_cells/include/*.*v* include 
cp /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/pulp_soc/../../rtl/includes/*.*v* include 
cp /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/pulp_soc/rtl/include/*.*v* include 
cp /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/pulp_soc/../axi/axi/include/*.*v* include 
cp /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/pulp_soc/../../rtl/includes/*.*v* include
cp /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/pulp_soc/./*.*v* include 
cp /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/pulp_soc/../../rtl/includes/*.*v* include 
cp /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/pulp_soc/./*.*v* include 
cp /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/pulp_soc/../../rtl/includes/*.*v* include 
