ln -s /home/victor/pulp_shared_vm/pulp_box/pulpissimo/rtl/includes/
ln -s /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/common_cells/include/
ln -s /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/cluster_interconnect/rtl/low_latency_interco/
ln -s /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/cluster_interconnect/rtl/peripheral_interco 
ln -s /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/cluster_interconnect/../../rtl/includes 
ln -s /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/adv_dbg_if/rtl 
ln -s /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/apb/apb_adv_timer/./rtl 
ln -s /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/axi/axi/include 
ln -s /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/axi/axi/../../common_cells/include 
ln -s /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/timer_unit/rtl 
ln -s /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/fpnew/../common_cells/include 
ln -s /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/jtag_pulp/../../rtl/includes 
ln -s /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/riscv/./rtl/include 
ln -s /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/riscv/../../rtl/includes 
ln -s /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/riscv/./rtl/include 
ln -s /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/ibex/rtl 
ln -s /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/ibex/shared/rtl 
ln -s /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/udma/udma_core/./rtl 
ln -s /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/udma/udma_qspi/rtl 
ln -s /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/hwpe-ctrl/rtl 
ln -s /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/hwpe-stream/rtl 
ln -s /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/hwpe-mac-engine/rtl 
ln -s /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/register_interface/include 
ln -s /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/register_interface/../axi/axi/include 
ln -s /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/register_interface/../common_cells/include 
ln -s /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/register_interface/include 
ln -s /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/register_interface/../axi/axi/include 
ln -s /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/register_interface/../common_cells/include 
ln -s /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/pulp_soc/../../rtl/includes 
ln -s /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/pulp_soc/rtl/include 
ln -s /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/pulp_soc/../axi/axi/include 
ln -s /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/pulp_soc/../../rtl/includes
ln -s /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/pulp_soc/. 
ln -s /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/pulp_soc/../../rtl/includes 
ln -s /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/pulp_soc/. 
ln -s /home/victor/pulp_shared_vm/pulp_box/pulpissimo/ips/pulp_soc/../../rtl/includes 
